// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIwU7iLEVNBVCo5RMlnhGSVUjrE6Dah1M',
    appId: '1:458262052410:web:0854c1513c2200d996ff03',
    messagingSenderId: '458262052410',
    projectId: 'mafia-party-game-bbf8b',
    authDomain: 'mafia-party-game-bbf8b.firebaseapp.com',
    storageBucket: 'mafia-party-game-bbf8b.firebasestorage.app',
    measurementId: 'G-BWJLCMP3YQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFKt4lyhuSy9VM27SeEI2k55ZPDWgCiGo',
    appId: '1:458262052410:android:ff9f66ae7737d9d496ff03',
    messagingSenderId: '458262052410',
    projectId: 'mafia-party-game-bbf8b',
    storageBucket: 'mafia-party-game-bbf8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk8LmFPmbDaY0i-rfwSpInEIBB-UVgNZE',
    appId: '1:458262052410:ios:c3a5b356bf97619796ff03',
    messagingSenderId: '458262052410',
    projectId: 'mafia-party-game-bbf8b',
    storageBucket: 'mafia-party-game-bbf8b.firebasestorage.app',
    iosBundleId: 'com.example.mafiaPartyGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk8LmFPmbDaY0i-rfwSpInEIBB-UVgNZE',
    appId: '1:458262052410:ios:c3a5b356bf97619796ff03',
    messagingSenderId: '458262052410',
    projectId: 'mafia-party-game-bbf8b',
    storageBucket: 'mafia-party-game-bbf8b.firebasestorage.app',
    iosBundleId: 'com.example.mafiaPartyGame',
  );

}